# Fast Preset
# Total sweep time: ~1-2 seconds
# Best for: High-speed drone flights, initial surveys
rtlConfig: &rtlConfig
  frequencyStart: 24000000     # 24 MHz
  frequencyEnd: 1766000000     # 1766 MHz
  binWidth: 100000             # 100 kHz steps
  interval: 1s                 # 1s integration
  crop: 0.15                   # Minimal cropping
  gain: 40                     # High gain
  smoothing: iir               # Fast smoothing
  windowFunction: rectangle    # Fastest window
  fftThreads: 2                # Parallel processing
# Spatial resolution at different drone speeds:
# - At 5 m/s: point every 10 meters
# - At 10 m/s: point every 20 meters

# Fast Preset
# Total sweep time: ~1-2 seconds
# Best for: High-speed drone flights, initial surveys
hackRFConfig: &hackRFConfig
  frequencyStart: 1000000      # 1 MHz
  frequencyEnd: 6000000000     # 6 Ghz
  binWidth: 200000             # 200 kHz steps (increased due to HackRF's wider bandwidth)
  lnaGain: 24                  # High LNA gain (0-40 dB)
  vgaGain: 36                  # High VGA gain (0-62 dB)
  enableAmp: true              # Enable amplifier for better sensitivity
# Spatial resolution at different drone speeds:
# - At 5 m/s: point every 8-10 meters
# - At 10 m/s: point every 15-20 meters

# Global application settings
settings:
  logLevel: "info"                   # debug, info, warn, error

# Device configurations
devices:
  # RTL-SDR device example
  - name: "Main Scanner"             # Human readable identifier
    type: "rtl-sdr"                  # Device type (rtl-sdr or hackrf)
    enabled: true                    # Whether this device should be used
    config: *rtlConfig               # Device configuration

  # HackRF device example
  - name: "Wide Scanner"             # Human readable identifier
    type: "hackrf"                   # Device type
    enabled: true                    # Whether this device should be used
    config: *hackRFConfig            # Device configuration

# Telemetry configuration
telemetry:
  serialPort: "/dev/ttyUSB0"         # Serial port for telemetry data
  baudRate: 115200                   # Serial port baud rate
  updateInterval: 0.1                # Telemetry update interval in seconds
  enabled: true                      # Enable telemetry collection
  types:
    - gps
    - imu
    - radio
    - barometer
    - magnetometer

# Storage configuration
storage:
  dataDirectory: "data"              # Directory for storing session databases
  maxBatchSize: 100                  # Maximum samples per batch insert