# Balanced Preset
# Total sweep time: ~3-4 seconds
# Best for: Medium-speed flights, general scanning
rtlConfig: &rtlConfig
  frequencyStart: 24000000     # 24 MHz
  frequencyEnd: 1766000000     # 1766 MHz
  binWidth: 50000              # 50 kHz steps - better resolution
  interval: 1s                 # 1s integration
  crop: 0.2                    # Standard cropping
  gain: 35                     # Balanced gain
  smoothing: avg               # Average smoothing for better accuracy
  windowFunction: hamming      # Better spectral accuracy
  fftThreads: 2                # Parallel processing
  peakHold: true               # Keep track of peaks during interval
# Spatial resolution at different drone speeds:
# - At 5 m/s: point every 20 meters
# - At 10 m/s: point every 40 meters

# Balanced Preset
# Total sweep time: ~3-4 seconds
# Best for: Medium-speed flights, general scanning
hackRFConfig: &hackRFConfig
  frequencyStart: 1000000      # 1 MHz
  frequencyEnd: 6000000000     # 6 Ghz
  binWidth: 100000             # 100 kHz steps - balanced resolution
  lnaGain: 20                  # Balanced LNA gain
  vgaGain: 32                  # Balanced VGA gain
  enableAmp: true              # Enable amp but with moderate gains
# Spatial resolution at different drone speeds:
# - At 5 m/s: point every 15-20 meters
# - At 10 m/s: point every 30-40 meters

# Global application settings
settings:
  logLevel: "info"                   # debug, info, warn, error

# Device configurations
devices:
  # RTL-SDR device example
  - name: "Main Scanner"             # Human readable identifier
    type: "rtl-sdr"                  # Device type (rtl-sdr or hackrf)
    enabled: true                    # Whether this device should be used
    config: *rtlConfig               # Device configuration

  # HackRF device example
  - name: "Wide Scanner"             # Human readable identifier
    type: "hackrf"                   # Device type
    enabled: true                    # Whether this device should be used
    config: *hackRFConfig            # Device configuration

# Telemetry configuration
telemetry:
  serialPort: "/dev/ttyUSB0"         # Serial port for telemetry data
  baudRate: 115200                   # Serial port baud rate
  updateInterval: 0.1                # Telemetry update interval in seconds
  enabled: true                      # Enable telemetry collection
  types:
    - gps
    - imu
    - radio
    - barometer
    - magnetometer

# Storage configuration
storage:
  dataDirectory: "data"              # Directory for storing session databases
  maxBatchSize: 100                  # Maximum samples per batch insert