# Fast Preset
# Total sweep time: ~1-2 seconds
# Best for: High-speed drone flights, initial surveys
rtlConfig: &rtlConfig
  frequencyStart: 24000000     # 24 MHz
  frequencyEnd: 1766000000     # 1766 MHz
  binSize: 100000              # 100 kHz steps
  interval: 0.1s               # 100ms integration
  cropPercent: 15              # Minimal cropping
  gain: 40                     # High gain
  smoothing: iir               # Fast smoothing
  windowFunction: rectangle    # Fastest window
  fftThreads: 2               # Parallel processing
# Spatial resolution at different drone speeds:
# - At 5 m/s: point every 10 meters
# - At 10 m/s: point every 20 meters

# Fast Preset
# Total sweep time: ~1-2 seconds
# Best for: High-speed drone flights, initial surveys
hackRFConfig: &hackRFConfig
  frequencyStart: 24000000     # 24 MHz
  frequencyEnd: 1766000000     # 1766 MHz
  binSize: 200000              # 200 kHz steps (increased due to HackRF's wider bandwidth)
  sampleRate: 20000000         # 20 MSPS - maximum for speed
  bandwidth: 20000000          # 20 MHz instantaneous bandwidth
  lnaGain: 24                  # High LNA gain (0-40 dB)
  vgaGain: 36                  # High VGA gain (0-62 dB)
  enableAmp: true              # Enable amplifier for better sensitivity
  fftSize: 256                 # Smaller FFT size for speed
  minFrequencySpacing: 20000000 # Match bandwidth for continuous coverage
  dwellTime: 128               # Minimum dwell time (in FFT bins)
  hopTime: 10000              # 10ms hop time between frequencies
# Spatial resolution at different drone speeds:
# - At 5 m/s: point every 8-10 meters
# - At 10 m/s: point every 15-20 meters

# Global application settings
settings:
  logLevel: "info"                   # debug, info, warn, error

# Device configurations
devices:
  # RTL-SDR device example
  - name: "Main Scanner"             # Human readable identifier
    type: "rtl-sdr"                  # Device type (rtl-sdr or hackrf)
    enabled: true                    # Whether this device should be used
    config: *rtlConfig               # Device configuration

  # HackRF device example
  - name: "Wide Scanner"             # Human readable identifier
    type: "hackrf"                   # Device type
    enabled: false                   # Whether this device should be used
    config: *hackRFConfig            # Device configuration

# Telemetry configuration
telemetry:
  serialPort: "/dev/ttyUSB0"         # Serial port for telemetry data
  baudRate: 115200                   # Serial port baud rate
  updateInterval: 0.1                # Telemetry update interval in seconds
  enabled: false                     # Enable telemetry collection
  types:
    - gps
    - imu
    - radio
    - barometer
    - magnetometer

# Storage configuration
storage:
  dataDirectory: "data"              # Directory for storing session databases
  maxBatchSize: 100                  # Maximum samples per batch insert